defmodule Helpdesk.Repo.Migrations.Test do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add(:representative_id, :uuid)
    end
  end

  def down do
    alter table(:tickets) do
      remove(:representative_id)
    end
  end
end
